### ISSUE TITLE
Generates Impossible Triangles

### ISSUE THREAD

**Issue by danfiscus** [danfiscus/solveit-gen#2]
# gen.py Problem:

The gen.py program generates unsolvable triangles. For example, it generated a triangle whose sides I inputted into the solver:
### Input (from Generator)

<code>float s1 = 1720.11668007;</code>
<code>float s2 = 311.355139483;</code>
<code>float s3 = 1413.33696394;</code>
This is actually an insolvable triangle! (See below):
### Output (from Solver)

![screen shot 2015-03-15 at 4 39 13 pm](https://cloud.githubusercontent.com/assets/8755783/6658002/d35674e2-cb31-11e4-9302-58d148370d72.png)
### Analysis

According to Chris, this could be due to a rounding error. He says "s1 is exactly s2+s3 in these rounded forms."
<hl>
P.S. This bug report is fancy because I felt like trying out markdown stuff. Yay!

**Comment by ChristopherKing42** [comment]
what were the angles supposed to be?

**Comment by danfiscus** [comment]
@TheKing42 I don't know - I didn't record them anywhere.

**Comment by ChristopherKing42** [comment]
I will make the program slightly more robust, so it is not at risk of rounding errors

**Comment by danfiscus** [comment]
@TheKing42 Ok. I am not exactly sure I understand what happened though. What caused it to generate invalidly?

**Comment by ChristopherKing42** [comment]
It must have generated an angle that was so close to 0, the sides rounded to a bad value.

**Comment by ChristopherKing42** [comment]
Now angles must be between 0.1 and pi-0.2

**Comment by danfiscus** [comment]
# It's still happening

It happened again... I'm not sure whether it's the generator not generating properly or the solver not solving correctly. I'm reopening the issue under the assumption that it's still the generator.

### Generator

Here's what the generator spit out when I ran it (after the "fix"):
![screen shot 2015-03-15 at 5 00 49 pm](https://cloud.githubusercontent.com/assets/8755783/6658094/d937e1f4-cb34-11e4-8207-cfdf9abe0a73.png)
Specifically, I'm looking at the side lengths a, b, and c:

```
a≈2080.26370467
b≈885.569781141
c≈1327.17001098
```

### Output

I inputted those side lengths into the solver...

``` C++
int main()
{
    float a1;
    float a2;
    float a3;
    float s1 = 2080.26370467;
    float s2 = 885.569781141;
    float s3 = 1327.17001098;
    triangle_solver(&a1,&a2,&a3,&s1,&s2,&s3);
    cout << "Done" << endl;
    return 0;
}
```

...and it gave me this result when I ran it:
![screen shot 2015-03-15 at 5 04 31 pm](https://cloud.githubusercontent.com/assets/8755783/6658105/5cadfbc2-cb35-11e4-930e-18906b7e51b8.png)

### Data

| Value | Generator | Solver |
| --- | --- | --- |
| s1/a | a≈2080.26370467 | s1: 2080.26 |
| s2/b | b≈885.569781141 | s2: 753.093 |
| s3/c | c≈1327.17001098 | s3: 1327.17 |
| a1/alpha | alpha≈2.4311196531radians≈139.292895614degrees | a1: nan |
| a2/beta | beta≈0.281335387726radians≈16.1193303444degrees | a2: 0 |
| a3/gamma | gamma≈0.42913761276radians≈24.5877740415degress | a3: nan |

### Note

P.S. On a side note, you misspelled "degrees" in the generator... It's not "degress". :wink:

**Comment by ChristopherKing42** [comment]
The triangle is fine: http://www.calculator.net/triangle-calculator.html?vc=&vx=2080&vy=885&va=&vz=1327&vb=&angleunits=d&x=41&y=7. This is an error with the solver.
